// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Renova.Persistence;

#nullable disable

namespace Renova.Persistence.Migrations
{
    [DbContext(typeof(RenovaDbContext))]
    [Migration("20260401191154_Exemplo")]
    partial class Exemplo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Renova.Domain.Model.RenovaModel", b =>
                {
                    b.Property<int>("Campo1")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Campo1"));

                    b.Property<string>("Campo2")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Campo3")
                        .HasColumnType("integer");

                    b.HasKey("Campo1");

                    b.HasIndex("Campo1");

                    b.ToTable("Renova", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
