// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Renova.Persistence;

#nullable disable

namespace Renova.Persistence.Migrations
{
    [DbContext(typeof(RenovaDbContext))]
    [Migration("20260416191232_CargosNormalizados")]
    partial class CargosNormalizados
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Renova.Domain.Model.CargoFuncionalidadeModel", b =>
                {
                    b.Property<int>("CargoId")
                        .HasColumnType("integer");

                    b.Property<int>("FuncionalidadeId")
                        .HasColumnType("integer");

                    b.HasKey("CargoId", "FuncionalidadeId");

                    b.HasIndex("FuncionalidadeId");

                    b.ToTable("CargoFuncionalidade", (string)null);
                });

            modelBuilder.Entity("Renova.Domain.Model.CargoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("LojaId")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("LojaId", "Nome")
                        .IsUnique();

                    b.ToTable("Cargo", (string)null);
                });

            modelBuilder.Entity("Renova.Domain.Model.ClienteCreditoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<int>("LojaId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId")
                        .IsUnique();

                    b.HasIndex("LojaId");

                    b.ToTable("ClienteCredito", (string)null);
                });

            modelBuilder.Entity("Renova.Domain.Model.ClienteModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Contato")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("Doacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("LojaId")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("LojaId", "Nome")
                        .IsUnique();

                    b.ToTable("Cliente", null, t =>
                        {
                            t.HasCheckConstraint("CK_Cliente_Contato_ApenasNumeros", "\"Contato\" !~ '[^0-9]' AND length(\"Contato\") IN (10, 11)");
                        });
                });

            modelBuilder.Entity("Renova.Domain.Model.ConfigLojaDescontoPermanenciaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("APartirDeMeses")
                        .HasColumnType("integer");

                    b.Property<int>("ConfigLojaId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PercentualDesconto")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("ConfigLojaId", "APartirDeMeses")
                        .IsUnique();

                    b.ToTable("ConfigLojaDescontoPermanencia", (string)null);
                });

            modelBuilder.Entity("Renova.Domain.Model.ConfigLojaFormaPagamentoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ConfigLojaId")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("PercentualAjuste")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("ConfigLojaId", "Nome")
                        .IsUnique();

                    b.ToTable("ConfigLojaFormaPagamento", (string)null);
                });

            modelBuilder.Entity("Renova.Domain.Model.ConfigLojaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("LojaId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PercentualRepasseFornecedor")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal>("PercentualRepasseVendedorCredito")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<int>("TempoPermanenciaProdutoMeses")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LojaId")
                        .IsUnique();

                    b.ToTable("ConfigLoja", (string)null);
                });

            modelBuilder.Entity("Renova.Domain.Model.CorModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("LojaId")
                        .HasColumnType("integer");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("LojaId", "Valor")
                        .IsUnique();

                    b.ToTable("Cor", (string)null);
                });

            modelBuilder.Entity("Renova.Domain.Model.FuncionalidadeModel", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Chave")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Grupo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Chave")
                        .IsUnique();

                    b.ToTable("Funcionalidade", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Chave = "clientes.visualizar",
                            Descricao = "Listar os clientes da loja.",
                            Grupo = "Clientes"
                        },
                        new
                        {
                            Id = 2,
                            Chave = "clientes.visualizar_detalhe",
                            Descricao = "Visualizar o detalhe e historico de um cliente.",
                            Grupo = "Clientes"
                        },
                        new
                        {
                            Id = 3,
                            Chave = "clientes.adicionar",
                            Descricao = "Cadastrar novos clientes.",
                            Grupo = "Clientes"
                        },
                        new
                        {
                            Id = 4,
                            Chave = "clientes.editar",
                            Descricao = "Editar clientes existentes.",
                            Grupo = "Clientes"
                        },
                        new
                        {
                            Id = 5,
                            Chave = "clientes.excluir",
                            Descricao = "Excluir clientes sem relacionamentos ativos.",
                            Grupo = "Clientes"
                        },
                        new
                        {
                            Id = 6,
                            Chave = "clientes.exportar_fechamento",
                            Descricao = "Exportar o fechamento de clientes.",
                            Grupo = "Clientes"
                        },
                        new
                        {
                            Id = 7,
                            Chave = "produtos.visualizar",
                            Descricao = "Listar os produtos da loja.",
                            Grupo = "Produtos"
                        },
                        new
                        {
                            Id = 8,
                            Chave = "produtos.visualizar_item",
                            Descricao = "Visualizar os dados de um produto.",
                            Grupo = "Produtos"
                        },
                        new
                        {
                            Id = 9,
                            Chave = "produtos.adicionar",
                            Descricao = "Cadastrar novos produtos no estoque.",
                            Grupo = "Produtos"
                        },
                        new
                        {
                            Id = 10,
                            Chave = "produtos.editar",
                            Descricao = "Editar produtos existentes.",
                            Grupo = "Produtos"
                        },
                        new
                        {
                            Id = 11,
                            Chave = "produtos.excluir",
                            Descricao = "Excluir produtos sem movimentacoes.",
                            Grupo = "Produtos"
                        },
                        new
                        {
                            Id = 12,
                            Chave = "produtos.emprestados.visualizar",
                            Descricao = "Consultar produtos emprestados por cliente.",
                            Grupo = "Produtos"
                        },
                        new
                        {
                            Id = 13,
                            Chave = "produtos.auxiliares.visualizar",
                            Descricao = "Consultar referencias, marcas, tamanhos e cores.",
                            Grupo = "Produtos"
                        },
                        new
                        {
                            Id = 14,
                            Chave = "produtos.auxiliares.adicionar_referencia",
                            Descricao = "Cadastrar novas referencias de produto.",
                            Grupo = "Produtos"
                        },
                        new
                        {
                            Id = 15,
                            Chave = "produtos.auxiliares.adicionar_marca",
                            Descricao = "Cadastrar novas marcas.",
                            Grupo = "Produtos"
                        },
                        new
                        {
                            Id = 16,
                            Chave = "produtos.auxiliares.adicionar_tamanho",
                            Descricao = "Cadastrar novos tamanhos.",
                            Grupo = "Produtos"
                        },
                        new
                        {
                            Id = 17,
                            Chave = "produtos.auxiliares.adicionar_cor",
                            Descricao = "Cadastrar novas cores.",
                            Grupo = "Produtos"
                        },
                        new
                        {
                            Id = 18,
                            Chave = "solicitacoes.visualizar",
                            Descricao = "Listar solicitacoes da loja.",
                            Grupo = "Solicitacoes"
                        },
                        new
                        {
                            Id = 19,
                            Chave = "solicitacoes.adicionar",
                            Descricao = "Cadastrar novas solicitacoes.",
                            Grupo = "Solicitacoes"
                        },
                        new
                        {
                            Id = 20,
                            Chave = "movimentacoes.visualizar",
                            Descricao = "Listar movimentacoes da loja.",
                            Grupo = "Movimentacoes"
                        },
                        new
                        {
                            Id = 21,
                            Chave = "movimentacoes.adicionar",
                            Descricao = "Registrar novas movimentacoes.",
                            Grupo = "Movimentacoes"
                        },
                        new
                        {
                            Id = 22,
                            Chave = "movimentacoes.destinacao.visualizar",
                            Descricao = "Consultar sugestoes para doacao e devolucao.",
                            Grupo = "Movimentacoes"
                        },
                        new
                        {
                            Id = 23,
                            Chave = "movimentacoes.destinacao.executar",
                            Descricao = "Executar destinacoes de doacao e devolucao.",
                            Grupo = "Movimentacoes"
                        },
                        new
                        {
                            Id = 24,
                            Chave = "pagamentos.visualizar",
                            Descricao = "Listar pagamentos da loja.",
                            Grupo = "Pagamentos"
                        },
                        new
                        {
                            Id = 25,
                            Chave = "pagamentos.manuais.adicionar",
                            Descricao = "Lancar pagamentos manuais.",
                            Grupo = "Pagamentos"
                        },
                        new
                        {
                            Id = 26,
                            Chave = "pagamentos.credito.visualizar",
                            Descricao = "Listar pagamentos de credito.",
                            Grupo = "Pagamentos"
                        },
                        new
                        {
                            Id = 27,
                            Chave = "pagamentos.credito.adicionar",
                            Descricao = "Adicionar credito para cliente.",
                            Grupo = "Pagamentos"
                        },
                        new
                        {
                            Id = 28,
                            Chave = "pagamentos.credito.resgatar",
                            Descricao = "Resgatar credito de cliente.",
                            Grupo = "Pagamentos"
                        },
                        new
                        {
                            Id = 29,
                            Chave = "pagamentos.pendencias.visualizar",
                            Descricao = "Visualizar pendencias de credito.",
                            Grupo = "Pagamentos"
                        },
                        new
                        {
                            Id = 30,
                            Chave = "pagamentos.pendencias.atualizar",
                            Descricao = "Atualizar pendencias de credito.",
                            Grupo = "Pagamentos"
                        },
                        new
                        {
                            Id = 31,
                            Chave = "pagamentos.fechamento.visualizar",
                            Descricao = "Visualizar o fechamento da loja.",
                            Grupo = "Pagamentos"
                        },
                        new
                        {
                            Id = 32,
                            Chave = "gastos_loja.visualizar",
                            Descricao = "Listar gastos da loja.",
                            Grupo = "GastosLoja"
                        },
                        new
                        {
                            Id = 33,
                            Chave = "gastos_loja.adicionar",
                            Descricao = "Cadastrar gastos e recebimentos da loja.",
                            Grupo = "GastosLoja"
                        },
                        new
                        {
                            Id = 34,
                            Chave = "lojas.visualizar",
                            Descricao = "Visualizar as lojas acessiveis.",
                            Grupo = "Lojas"
                        },
                        new
                        {
                            Id = 35,
                            Chave = "lojas.adicionar",
                            Descricao = "Cadastrar novas lojas.",
                            Grupo = "Lojas"
                        },
                        new
                        {
                            Id = 36,
                            Chave = "lojas.editar",
                            Descricao = "Editar lojas existentes.",
                            Grupo = "Lojas"
                        },
                        new
                        {
                            Id = 37,
                            Chave = "lojas.excluir",
                            Descricao = "Excluir lojas sem registros ativos.",
                            Grupo = "Lojas"
                        },
                        new
                        {
                            Id = 38,
                            Chave = "config_loja.visualizar",
                            Descricao = "Visualizar configuracoes da loja.",
                            Grupo = "ConfiguracaoLoja"
                        },
                        new
                        {
                            Id = 39,
                            Chave = "config_loja.editar",
                            Descricao = "Editar configuracoes da loja.",
                            Grupo = "ConfiguracaoLoja"
                        },
                        new
                        {
                            Id = 40,
                            Chave = "funcionarios.visualizar",
                            Descricao = "Listar funcionarios da loja.",
                            Grupo = "Funcionarios"
                        },
                        new
                        {
                            Id = 41,
                            Chave = "funcionarios.adicionar",
                            Descricao = "Vincular funcionarios a loja.",
                            Grupo = "Funcionarios"
                        },
                        new
                        {
                            Id = 42,
                            Chave = "funcionarios.editar",
                            Descricao = "Alterar o cargo de funcionarios.",
                            Grupo = "Funcionarios"
                        },
                        new
                        {
                            Id = 43,
                            Chave = "funcionarios.remover",
                            Descricao = "Remover funcionarios da loja.",
                            Grupo = "Funcionarios"
                        },
                        new
                        {
                            Id = 44,
                            Chave = "cargos.visualizar",
                            Descricao = "Listar cargos e funcionalidades da loja.",
                            Grupo = "Cargos"
                        },
                        new
                        {
                            Id = 45,
                            Chave = "cargos.adicionar",
                            Descricao = "Cadastrar novos cargos.",
                            Grupo = "Cargos"
                        },
                        new
                        {
                            Id = 46,
                            Chave = "cargos.editar",
                            Descricao = "Editar cargos existentes.",
                            Grupo = "Cargos"
                        },
                        new
                        {
                            Id = 47,
                            Chave = "cargos.excluir",
                            Descricao = "Excluir cargos sem funcionarios vinculados.",
                            Grupo = "Cargos"
                        });
                });

            modelBuilder.Entity("Renova.Domain.Model.FuncionarioModel", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<int>("LojaId")
                        .HasColumnType("integer");

                    b.Property<int>("CargoId")
                        .HasColumnType("integer");

                    b.HasKey("UsuarioId", "LojaId");

                    b.HasIndex("CargoId");

                    b.HasIndex("LojaId");

                    b.ToTable("Funcionario", (string)null);
                });

            modelBuilder.Entity("Renova.Domain.Model.GastoLojaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("LojaId")
                        .HasColumnType("integer");

                    b.Property<int>("Natureza")
                        .HasColumnType("integer");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("LojaId");

                    b.ToTable("GastoLoja", (string)null);
                });

            modelBuilder.Entity("Renova.Domain.Model.LojaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "Nome")
                        .IsUnique();

                    b.ToTable("Loja", (string)null);
                });

            modelBuilder.Entity("Renova.Domain.Model.MarcaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("LojaId")
                        .HasColumnType("integer");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("LojaId", "Valor")
                        .IsUnique();

                    b.ToTable("Marca", (string)null);
                });

            modelBuilder.Entity("Renova.Domain.Model.MovimentacaoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LojaId")
                        .HasColumnType("integer");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("LojaId");

                    b.ToTable("Movimentacao", (string)null);
                });

            modelBuilder.Entity("Renova.Domain.Model.MovimentacaoProdutoModel", b =>
                {
                    b.Property<int>("MovimentacaoId")
                        .HasColumnType("integer");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Desconto")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.HasKey("MovimentacaoId", "ProdutoId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("MovimentacaoProduto", (string)null);
                });

            modelBuilder.Entity("Renova.Domain.Model.PagamentoCreditoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<int?>("ConfigLojaFormaPagamentoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LojaId")
                        .HasColumnType("integer");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<decimal>("ValorCredito")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("ValorDinheiro")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("ConfigLojaFormaPagamentoId");

                    b.HasIndex("LojaId");

                    b.ToTable("PagamentoCredito", (string)null);
                });

            modelBuilder.Entity("Renova.Domain.Model.PagamentoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("LojaId")
                        .HasColumnType("integer");

                    b.Property<int?>("MovimentacaoId")
                        .HasColumnType("integer");

                    b.Property<int>("Natureza")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("LojaId");

                    b.HasIndex("MovimentacaoId");

                    b.ToTable("Pagamento", (string)null);
                });

            modelBuilder.Entity("Renova.Domain.Model.ProdutoEstoqueModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Consignado")
                        .HasColumnType("boolean");

                    b.Property<int>("CorId")
                        .HasColumnType("integer");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("Entrada")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FornecedorId")
                        .HasColumnType("integer");

                    b.Property<int>("LojaId")
                        .HasColumnType("integer");

                    b.Property<int>("MarcaId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Preco")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("integer");

                    b.Property<int>("Situacao")
                        .HasColumnType("integer");

                    b.Property<int>("TamanhoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CorId");

                    b.HasIndex("FornecedorId");

                    b.HasIndex("LojaId");

                    b.HasIndex("MarcaId");

                    b.HasIndex("ProdutoId");

                    b.HasIndex("TamanhoId");

                    b.ToTable("ProdutoEstoque", (string)null);
                });

            modelBuilder.Entity("Renova.Domain.Model.ProdutoReferenciaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("LojaId")
                        .HasColumnType("integer");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("LojaId", "Valor")
                        .IsUnique();

                    b.ToTable("ProdutoReferencia", (string)null);
                });

            modelBuilder.Entity("Renova.Domain.Model.RenovaModel", b =>
                {
                    b.Property<int>("Campo1")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Campo1"));

                    b.Property<string>("Campo2")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Campo3")
                        .HasColumnType("integer");

                    b.HasKey("Campo1");

                    b.HasIndex("Campo1");

                    b.ToTable("Renova", (string)null);
                });

            modelBuilder.Entity("Renova.Domain.Model.SolicitacaoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<int>("CorId")
                        .HasColumnType("integer");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("LojaId")
                        .HasColumnType("integer");

                    b.Property<int>("MarcaId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PrecoMaximo")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("PrecoMinimo")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("integer");

                    b.Property<int>("TamanhoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("CorId");

                    b.HasIndex("LojaId");

                    b.HasIndex("MarcaId");

                    b.HasIndex("ProdutoId");

                    b.HasIndex("TamanhoId");

                    b.ToTable("Solicitacao", (string)null);
                });

            modelBuilder.Entity("Renova.Domain.Model.TamanhoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("LojaId")
                        .HasColumnType("integer");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("LojaId", "Valor")
                        .IsUnique();

                    b.ToTable("Tamanho", (string)null);
                });

            modelBuilder.Entity("Renova.Domain.Model.UsuarioModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("Renova.Domain.Model.CargoFuncionalidadeModel", b =>
                {
                    b.HasOne("Renova.Domain.Model.CargoModel", "Cargo")
                        .WithMany("Funcionalidades")
                        .HasForeignKey("CargoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Renova.Domain.Model.FuncionalidadeModel", "Funcionalidade")
                        .WithMany("Cargos")
                        .HasForeignKey("FuncionalidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cargo");

                    b.Navigation("Funcionalidade");
                });

            modelBuilder.Entity("Renova.Domain.Model.CargoModel", b =>
                {
                    b.HasOne("Renova.Domain.Model.LojaModel", "Loja")
                        .WithMany("Cargos")
                        .HasForeignKey("LojaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Loja");
                });

            modelBuilder.Entity("Renova.Domain.Model.ClienteCreditoModel", b =>
                {
                    b.HasOne("Renova.Domain.Model.ClienteModel", "Cliente")
                        .WithOne("Credito")
                        .HasForeignKey("Renova.Domain.Model.ClienteCreditoModel", "ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Renova.Domain.Model.LojaModel", "Loja")
                        .WithMany("CreditosClientes")
                        .HasForeignKey("LojaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Loja");
                });

            modelBuilder.Entity("Renova.Domain.Model.ClienteModel", b =>
                {
                    b.HasOne("Renova.Domain.Model.LojaModel", "Loja")
                        .WithMany("Clientes")
                        .HasForeignKey("LojaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Renova.Domain.Model.UsuarioModel", "User")
                        .WithMany("Clientes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Loja");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Renova.Domain.Model.ConfigLojaDescontoPermanenciaModel", b =>
                {
                    b.HasOne("Renova.Domain.Model.ConfigLojaModel", "ConfigLoja")
                        .WithMany("DescontosPermanencia")
                        .HasForeignKey("ConfigLojaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConfigLoja");
                });

            modelBuilder.Entity("Renova.Domain.Model.ConfigLojaFormaPagamentoModel", b =>
                {
                    b.HasOne("Renova.Domain.Model.ConfigLojaModel", "ConfigLoja")
                        .WithMany("FormasPagamento")
                        .HasForeignKey("ConfigLojaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConfigLoja");
                });

            modelBuilder.Entity("Renova.Domain.Model.ConfigLojaModel", b =>
                {
                    b.HasOne("Renova.Domain.Model.LojaModel", "Loja")
                        .WithOne("ConfigLoja")
                        .HasForeignKey("Renova.Domain.Model.ConfigLojaModel", "LojaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Loja");
                });

            modelBuilder.Entity("Renova.Domain.Model.CorModel", b =>
                {
                    b.HasOne("Renova.Domain.Model.LojaModel", "Loja")
                        .WithMany("Cores")
                        .HasForeignKey("LojaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Loja");
                });

            modelBuilder.Entity("Renova.Domain.Model.FuncionarioModel", b =>
                {
                    b.HasOne("Renova.Domain.Model.CargoModel", "Cargo")
                        .WithMany("Funcionarios")
                        .HasForeignKey("CargoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Renova.Domain.Model.LojaModel", "Loja")
                        .WithMany("Funcionarios")
                        .HasForeignKey("LojaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Renova.Domain.Model.UsuarioModel", "Usuario")
                        .WithMany("Funcionarios")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cargo");

                    b.Navigation("Loja");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Renova.Domain.Model.GastoLojaModel", b =>
                {
                    b.HasOne("Renova.Domain.Model.LojaModel", "Loja")
                        .WithMany("GastosLoja")
                        .HasForeignKey("LojaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Loja");
                });

            modelBuilder.Entity("Renova.Domain.Model.LojaModel", b =>
                {
                    b.HasOne("Renova.Domain.Model.UsuarioModel", "Usuario")
                        .WithMany("Lojas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Renova.Domain.Model.MarcaModel", b =>
                {
                    b.HasOne("Renova.Domain.Model.LojaModel", "Loja")
                        .WithMany("Marcas")
                        .HasForeignKey("LojaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Loja");
                });

            modelBuilder.Entity("Renova.Domain.Model.MovimentacaoModel", b =>
                {
                    b.HasOne("Renova.Domain.Model.ClienteModel", "Cliente")
                        .WithMany("Movimentacoes")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Renova.Domain.Model.LojaModel", "Loja")
                        .WithMany("Movimentacoes")
                        .HasForeignKey("LojaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Loja");
                });

            modelBuilder.Entity("Renova.Domain.Model.MovimentacaoProdutoModel", b =>
                {
                    b.HasOne("Renova.Domain.Model.MovimentacaoModel", "Movimentacao")
                        .WithMany("Produtos")
                        .HasForeignKey("MovimentacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Renova.Domain.Model.ProdutoEstoqueModel", "Produto")
                        .WithMany("Movimentacoes")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Movimentacao");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("Renova.Domain.Model.PagamentoCreditoModel", b =>
                {
                    b.HasOne("Renova.Domain.Model.ClienteModel", "Cliente")
                        .WithMany("PagamentosCredito")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Renova.Domain.Model.ConfigLojaFormaPagamentoModel", "ConfigLojaFormaPagamento")
                        .WithMany()
                        .HasForeignKey("ConfigLojaFormaPagamentoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Renova.Domain.Model.LojaModel", "Loja")
                        .WithMany("PagamentosCredito")
                        .HasForeignKey("LojaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("ConfigLojaFormaPagamento");

                    b.Navigation("Loja");
                });

            modelBuilder.Entity("Renova.Domain.Model.PagamentoModel", b =>
                {
                    b.HasOne("Renova.Domain.Model.ClienteModel", "Cliente")
                        .WithMany("Pagamentos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Renova.Domain.Model.LojaModel", "Loja")
                        .WithMany("Pagamentos")
                        .HasForeignKey("LojaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Renova.Domain.Model.MovimentacaoModel", "Movimentacao")
                        .WithMany("Pagamentos")
                        .HasForeignKey("MovimentacaoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Cliente");

                    b.Navigation("Loja");

                    b.Navigation("Movimentacao");
                });

            modelBuilder.Entity("Renova.Domain.Model.ProdutoEstoqueModel", b =>
                {
                    b.HasOne("Renova.Domain.Model.CorModel", "Cor")
                        .WithMany("ProdutosEstoque")
                        .HasForeignKey("CorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Renova.Domain.Model.ClienteModel", "Fornecedor")
                        .WithMany("ProdutosFornecidos")
                        .HasForeignKey("FornecedorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Renova.Domain.Model.LojaModel", "Loja")
                        .WithMany("ProdutosEstoque")
                        .HasForeignKey("LojaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Renova.Domain.Model.MarcaModel", "Marca")
                        .WithMany("ProdutosEstoque")
                        .HasForeignKey("MarcaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Renova.Domain.Model.ProdutoReferenciaModel", "Produto")
                        .WithMany("ProdutosEstoque")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Renova.Domain.Model.TamanhoModel", "Tamanho")
                        .WithMany("ProdutosEstoque")
                        .HasForeignKey("TamanhoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cor");

                    b.Navigation("Fornecedor");

                    b.Navigation("Loja");

                    b.Navigation("Marca");

                    b.Navigation("Produto");

                    b.Navigation("Tamanho");
                });

            modelBuilder.Entity("Renova.Domain.Model.ProdutoReferenciaModel", b =>
                {
                    b.HasOne("Renova.Domain.Model.LojaModel", "Loja")
                        .WithMany("ProdutosReferencia")
                        .HasForeignKey("LojaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Loja");
                });

            modelBuilder.Entity("Renova.Domain.Model.SolicitacaoModel", b =>
                {
                    b.HasOne("Renova.Domain.Model.ClienteModel", "Cliente")
                        .WithMany("Solicitacoes")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Renova.Domain.Model.CorModel", "Cor")
                        .WithMany()
                        .HasForeignKey("CorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Renova.Domain.Model.LojaModel", "Loja")
                        .WithMany("Solicitacoes")
                        .HasForeignKey("LojaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Renova.Domain.Model.MarcaModel", "Marca")
                        .WithMany()
                        .HasForeignKey("MarcaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Renova.Domain.Model.ProdutoReferenciaModel", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Renova.Domain.Model.TamanhoModel", "Tamanho")
                        .WithMany()
                        .HasForeignKey("TamanhoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Cor");

                    b.Navigation("Loja");

                    b.Navigation("Marca");

                    b.Navigation("Produto");

                    b.Navigation("Tamanho");
                });

            modelBuilder.Entity("Renova.Domain.Model.TamanhoModel", b =>
                {
                    b.HasOne("Renova.Domain.Model.LojaModel", "Loja")
                        .WithMany("Tamanhos")
                        .HasForeignKey("LojaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Loja");
                });

            modelBuilder.Entity("Renova.Domain.Model.CargoModel", b =>
                {
                    b.Navigation("Funcionalidades");

                    b.Navigation("Funcionarios");
                });

            modelBuilder.Entity("Renova.Domain.Model.ClienteModel", b =>
                {
                    b.Navigation("Credito");

                    b.Navigation("Movimentacoes");

                    b.Navigation("Pagamentos");

                    b.Navigation("PagamentosCredito");

                    b.Navigation("ProdutosFornecidos");

                    b.Navigation("Solicitacoes");
                });

            modelBuilder.Entity("Renova.Domain.Model.ConfigLojaModel", b =>
                {
                    b.Navigation("DescontosPermanencia");

                    b.Navigation("FormasPagamento");
                });

            modelBuilder.Entity("Renova.Domain.Model.CorModel", b =>
                {
                    b.Navigation("ProdutosEstoque");
                });

            modelBuilder.Entity("Renova.Domain.Model.FuncionalidadeModel", b =>
                {
                    b.Navigation("Cargos");
                });

            modelBuilder.Entity("Renova.Domain.Model.LojaModel", b =>
                {
                    b.Navigation("Cargos");

                    b.Navigation("Clientes");

                    b.Navigation("ConfigLoja");

                    b.Navigation("Cores");

                    b.Navigation("CreditosClientes");

                    b.Navigation("Funcionarios");

                    b.Navigation("GastosLoja");

                    b.Navigation("Marcas");

                    b.Navigation("Movimentacoes");

                    b.Navigation("Pagamentos");

                    b.Navigation("PagamentosCredito");

                    b.Navigation("ProdutosEstoque");

                    b.Navigation("ProdutosReferencia");

                    b.Navigation("Solicitacoes");

                    b.Navigation("Tamanhos");
                });

            modelBuilder.Entity("Renova.Domain.Model.MarcaModel", b =>
                {
                    b.Navigation("ProdutosEstoque");
                });

            modelBuilder.Entity("Renova.Domain.Model.MovimentacaoModel", b =>
                {
                    b.Navigation("Pagamentos");

                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("Renova.Domain.Model.ProdutoEstoqueModel", b =>
                {
                    b.Navigation("Movimentacoes");
                });

            modelBuilder.Entity("Renova.Domain.Model.ProdutoReferenciaModel", b =>
                {
                    b.Navigation("ProdutosEstoque");
                });

            modelBuilder.Entity("Renova.Domain.Model.TamanhoModel", b =>
                {
                    b.Navigation("ProdutosEstoque");
                });

            modelBuilder.Entity("Renova.Domain.Model.UsuarioModel", b =>
                {
                    b.Navigation("Clientes");

                    b.Navigation("Funcionarios");

                    b.Navigation("Lojas");
                });
#pragma warning restore 612, 618
        }
    }
}
