using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Renova.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class CorrigirSchemaMovimentacao : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(
                """
                CREATE TABLE IF NOT EXISTS "Movimentacao" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "Tipo" integer NOT NULL,
                    "Data" timestamp with time zone NOT NULL,
                    "ClienteId" integer NOT NULL,
                    "LojaId" integer NOT NULL,
                    CONSTRAINT "PK_Movimentacao" PRIMARY KEY ("Id"),
                    CONSTRAINT "FK_Movimentacao_Cliente_ClienteId" FOREIGN KEY ("ClienteId") REFERENCES "Cliente" ("Id") ON DELETE RESTRICT,
                    CONSTRAINT "FK_Movimentacao_Loja_LojaId" FOREIGN KEY ("LojaId") REFERENCES "Loja" ("Id") ON DELETE CASCADE
                );
                """);

            migrationBuilder.Sql(
                """
                CREATE TABLE IF NOT EXISTS "MovimentacaoProduto" (
                    "MovimentacaoId" integer NOT NULL,
                    "ProdutoId" integer NOT NULL,
                    CONSTRAINT "PK_MovimentacaoProduto" PRIMARY KEY ("MovimentacaoId", "ProdutoId"),
                    CONSTRAINT "FK_MovimentacaoProduto_Movimentacao_MovimentacaoId" FOREIGN KEY ("MovimentacaoId") REFERENCES "Movimentacao" ("Id") ON DELETE CASCADE,
                    CONSTRAINT "FK_MovimentacaoProduto_ProdutoEstoque_ProdutoId" FOREIGN KEY ("ProdutoId") REFERENCES "ProdutoEstoque" ("Id") ON DELETE RESTRICT
                );
                """);

            migrationBuilder.Sql("""CREATE INDEX IF NOT EXISTS "IX_Movimentacao_ClienteId" ON "Movimentacao" ("ClienteId");""");
            migrationBuilder.Sql("""CREATE INDEX IF NOT EXISTS "IX_Movimentacao_LojaId" ON "Movimentacao" ("LojaId");""");
            migrationBuilder.Sql("""CREATE INDEX IF NOT EXISTS "IX_MovimentacaoProduto_ProdutoId" ON "MovimentacaoProduto" ("ProdutoId");""");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""DROP TABLE IF EXISTS "MovimentacaoProduto";""");
            migrationBuilder.Sql("""DROP TABLE IF EXISTS "Movimentacao";""");
        }
    }
}
