// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Renova.Persistence;

#nullable disable

namespace Renova.Persistence.Migrations
{
    [DbContext(typeof(RenovaDbContext))]
    [Migration("20260409185547_ClienteCredito")]
    partial class ClienteCredito
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Renova.Domain.Model.ClienteCreditoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<int>("LojaId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId")
                        .IsUnique();

                    b.HasIndex("LojaId");

                    b.ToTable("ClienteCredito", (string)null);
                });

            modelBuilder.Entity("Renova.Domain.Model.ClienteModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Contato")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("Doacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("LojaId")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("LojaId", "Nome")
                        .IsUnique();

                    b.ToTable("Cliente", null, t =>
                        {
                            t.HasCheckConstraint("CK_Cliente_Contato_ApenasNumeros", "\"Contato\" !~ '[^0-9]' AND length(\"Contato\") IN (10, 11)");
                        });
                });

            modelBuilder.Entity("Renova.Domain.Model.ConfigLojaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("LojaId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PercentualRepasseFornecedor")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal>("PercentualRepasseVendedorCredito")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<int>("TempoPermanenciaProdutoMeses")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LojaId")
                        .IsUnique();

                    b.ToTable("ConfigLoja", (string)null);
                });

            modelBuilder.Entity("Renova.Domain.Model.CorModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("LojaId")
                        .HasColumnType("integer");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("LojaId", "Valor")
                        .IsUnique();

                    b.ToTable("Cor", (string)null);
                });

            modelBuilder.Entity("Renova.Domain.Model.LojaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "Nome")
                        .IsUnique();

                    b.ToTable("Loja", (string)null);
                });

            modelBuilder.Entity("Renova.Domain.Model.MarcaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("LojaId")
                        .HasColumnType("integer");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("LojaId", "Valor")
                        .IsUnique();

                    b.ToTable("Marca", (string)null);
                });

            modelBuilder.Entity("Renova.Domain.Model.MovimentacaoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LojaId")
                        .HasColumnType("integer");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("LojaId");

                    b.ToTable("Movimentacao", (string)null);
                });

            modelBuilder.Entity("Renova.Domain.Model.MovimentacaoProdutoModel", b =>
                {
                    b.Property<int>("MovimentacaoId")
                        .HasColumnType("integer");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("integer");

                    b.HasKey("MovimentacaoId", "ProdutoId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("MovimentacaoProduto", (string)null);
                });

            modelBuilder.Entity("Renova.Domain.Model.PagamentoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LojaId")
                        .HasColumnType("integer");

                    b.Property<int>("MovimentacaoId")
                        .HasColumnType("integer");

                    b.Property<int>("Natureza")
                        .HasColumnType("integer");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("LojaId");

                    b.HasIndex("MovimentacaoId");

                    b.ToTable("Pagamento", (string)null);
                });

            modelBuilder.Entity("Renova.Domain.Model.ProdutoEstoqueModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Consignado")
                        .HasColumnType("boolean");

                    b.Property<int>("CorId")
                        .HasColumnType("integer");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("Entrada")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FornecedorId")
                        .HasColumnType("integer");

                    b.Property<int>("LojaId")
                        .HasColumnType("integer");

                    b.Property<int>("MarcaId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Preco")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("integer");

                    b.Property<int>("Situacao")
                        .HasColumnType("integer");

                    b.Property<int>("TamanhoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CorId");

                    b.HasIndex("FornecedorId");

                    b.HasIndex("LojaId");

                    b.HasIndex("MarcaId");

                    b.HasIndex("ProdutoId");

                    b.HasIndex("TamanhoId");

                    b.ToTable("ProdutoEstoque", (string)null);
                });

            modelBuilder.Entity("Renova.Domain.Model.ProdutoReferenciaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("LojaId")
                        .HasColumnType("integer");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("LojaId", "Valor")
                        .IsUnique();

                    b.ToTable("ProdutoReferencia", (string)null);
                });

            modelBuilder.Entity("Renova.Domain.Model.RenovaModel", b =>
                {
                    b.Property<int>("Campo1")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Campo1"));

                    b.Property<string>("Campo2")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Campo3")
                        .HasColumnType("integer");

                    b.HasKey("Campo1");

                    b.HasIndex("Campo1");

                    b.ToTable("Renova", (string)null);
                });

            modelBuilder.Entity("Renova.Domain.Model.TamanhoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("LojaId")
                        .HasColumnType("integer");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("LojaId", "Valor")
                        .IsUnique();

                    b.ToTable("Tamanho", (string)null);
                });

            modelBuilder.Entity("Renova.Domain.Model.UsuarioModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("Renova.Domain.Model.ClienteCreditoModel", b =>
                {
                    b.HasOne("Renova.Domain.Model.ClienteModel", "Cliente")
                        .WithOne("Credito")
                        .HasForeignKey("Renova.Domain.Model.ClienteCreditoModel", "ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Renova.Domain.Model.LojaModel", "Loja")
                        .WithMany("CreditosClientes")
                        .HasForeignKey("LojaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Loja");
                });

            modelBuilder.Entity("Renova.Domain.Model.ClienteModel", b =>
                {
                    b.HasOne("Renova.Domain.Model.LojaModel", "Loja")
                        .WithMany("Clientes")
                        .HasForeignKey("LojaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Renova.Domain.Model.UsuarioModel", "User")
                        .WithMany("Clientes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Loja");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Renova.Domain.Model.ConfigLojaModel", b =>
                {
                    b.HasOne("Renova.Domain.Model.LojaModel", "Loja")
                        .WithOne("ConfigLoja")
                        .HasForeignKey("Renova.Domain.Model.ConfigLojaModel", "LojaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Loja");
                });

            modelBuilder.Entity("Renova.Domain.Model.CorModel", b =>
                {
                    b.HasOne("Renova.Domain.Model.LojaModel", "Loja")
                        .WithMany("Cores")
                        .HasForeignKey("LojaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Loja");
                });

            modelBuilder.Entity("Renova.Domain.Model.LojaModel", b =>
                {
                    b.HasOne("Renova.Domain.Model.UsuarioModel", "Usuario")
                        .WithMany("Lojas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Renova.Domain.Model.MarcaModel", b =>
                {
                    b.HasOne("Renova.Domain.Model.LojaModel", "Loja")
                        .WithMany("Marcas")
                        .HasForeignKey("LojaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Loja");
                });

            modelBuilder.Entity("Renova.Domain.Model.MovimentacaoModel", b =>
                {
                    b.HasOne("Renova.Domain.Model.ClienteModel", "Cliente")
                        .WithMany("Movimentacoes")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Renova.Domain.Model.LojaModel", "Loja")
                        .WithMany("Movimentacoes")
                        .HasForeignKey("LojaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Loja");
                });

            modelBuilder.Entity("Renova.Domain.Model.MovimentacaoProdutoModel", b =>
                {
                    b.HasOne("Renova.Domain.Model.MovimentacaoModel", "Movimentacao")
                        .WithMany("Produtos")
                        .HasForeignKey("MovimentacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Renova.Domain.Model.ProdutoEstoqueModel", "Produto")
                        .WithMany("Movimentacoes")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Movimentacao");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("Renova.Domain.Model.PagamentoModel", b =>
                {
                    b.HasOne("Renova.Domain.Model.ClienteModel", "Cliente")
                        .WithMany("Pagamentos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Renova.Domain.Model.LojaModel", "Loja")
                        .WithMany("Pagamentos")
                        .HasForeignKey("LojaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Renova.Domain.Model.MovimentacaoModel", "Movimentacao")
                        .WithMany("Pagamentos")
                        .HasForeignKey("MovimentacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Loja");

                    b.Navigation("Movimentacao");
                });

            modelBuilder.Entity("Renova.Domain.Model.ProdutoEstoqueModel", b =>
                {
                    b.HasOne("Renova.Domain.Model.CorModel", "Cor")
                        .WithMany("ProdutosEstoque")
                        .HasForeignKey("CorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Renova.Domain.Model.ClienteModel", "Fornecedor")
                        .WithMany("ProdutosFornecidos")
                        .HasForeignKey("FornecedorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Renova.Domain.Model.LojaModel", "Loja")
                        .WithMany("ProdutosEstoque")
                        .HasForeignKey("LojaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Renova.Domain.Model.MarcaModel", "Marca")
                        .WithMany("ProdutosEstoque")
                        .HasForeignKey("MarcaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Renova.Domain.Model.ProdutoReferenciaModel", "Produto")
                        .WithMany("ProdutosEstoque")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Renova.Domain.Model.TamanhoModel", "Tamanho")
                        .WithMany("ProdutosEstoque")
                        .HasForeignKey("TamanhoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cor");

                    b.Navigation("Fornecedor");

                    b.Navigation("Loja");

                    b.Navigation("Marca");

                    b.Navigation("Produto");

                    b.Navigation("Tamanho");
                });

            modelBuilder.Entity("Renova.Domain.Model.ProdutoReferenciaModel", b =>
                {
                    b.HasOne("Renova.Domain.Model.LojaModel", "Loja")
                        .WithMany("ProdutosReferencia")
                        .HasForeignKey("LojaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Loja");
                });

            modelBuilder.Entity("Renova.Domain.Model.TamanhoModel", b =>
                {
                    b.HasOne("Renova.Domain.Model.LojaModel", "Loja")
                        .WithMany("Tamanhos")
                        .HasForeignKey("LojaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Loja");
                });

            modelBuilder.Entity("Renova.Domain.Model.ClienteModel", b =>
                {
                    b.Navigation("Credito");

                    b.Navigation("Movimentacoes");

                    b.Navigation("Pagamentos");

                    b.Navigation("ProdutosFornecidos");
                });

            modelBuilder.Entity("Renova.Domain.Model.CorModel", b =>
                {
                    b.Navigation("ProdutosEstoque");
                });

            modelBuilder.Entity("Renova.Domain.Model.LojaModel", b =>
                {
                    b.Navigation("Clientes");

                    b.Navigation("ConfigLoja");

                    b.Navigation("Cores");

                    b.Navigation("CreditosClientes");

                    b.Navigation("Marcas");

                    b.Navigation("Movimentacoes");

                    b.Navigation("Pagamentos");

                    b.Navigation("ProdutosEstoque");

                    b.Navigation("ProdutosReferencia");

                    b.Navigation("Tamanhos");
                });

            modelBuilder.Entity("Renova.Domain.Model.MarcaModel", b =>
                {
                    b.Navigation("ProdutosEstoque");
                });

            modelBuilder.Entity("Renova.Domain.Model.MovimentacaoModel", b =>
                {
                    b.Navigation("Pagamentos");

                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("Renova.Domain.Model.ProdutoEstoqueModel", b =>
                {
                    b.Navigation("Movimentacoes");
                });

            modelBuilder.Entity("Renova.Domain.Model.ProdutoReferenciaModel", b =>
                {
                    b.Navigation("ProdutosEstoque");
                });

            modelBuilder.Entity("Renova.Domain.Model.TamanhoModel", b =>
                {
                    b.Navigation("ProdutosEstoque");
                });

            modelBuilder.Entity("Renova.Domain.Model.UsuarioModel", b =>
                {
                    b.Navigation("Clientes");

                    b.Navigation("Lojas");
                });
#pragma warning restore 612, 618
        }
    }
}
