// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Renova.Persistence;

#nullable disable

namespace Persistencia.Migrations
{
    [DbContext(typeof(RenovaDbContext))]
    [Migration("20260317133000_RemoveLojaConfiguracao")]
    partial class RemoveLojaConfiguracao
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
